name: Compile AHK Script
description: Compile both v1 and v2 AutoHotkey scripts using Ahk2Exe from Github
author: Banaanae

inputs:
  in:
    description: Name (and path if not root) of file to compile, (newline separated)
    required: true
  out:
    description: Name (and path if not root) for the compiled files (must match input order)
    required: false
  version:
    description: Version to compile with, as a Github tag
    required: false
    default: "latest"
  bits:
    description: Compiler bit count (also specify U before bits for unicode, v1 only)
    required: false
    default: 64

runs:
  using: composite
  steps:
    - name: Install AutoHotkey and Ahk2Exe
      shell: pwsh
      run: |
        $compileTag = "${{inputs.version}}"
        $releases = "https://api.github.com/repos/AutoHotkey/Ahk2Exe/releases"
        $ahk2exeDL = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].assets[0].browser_download_url
        Invoke-WebRequest "$ahk2exeDL" -Out "ahk.zip"
        Expand-Archive "ahk.zip" -Force
        $scriptDir = Get-Location
        $compileExe = Join-Path -Path (Join-Path -Path $scriptDir -ChildPath "ahk") -ChildPath "Ahk2Exe.exe"

        if($compileTag -eq "latest"){
          $releasesAHK = "https://api.github.com/repos/AutoHotkey/AutoHotkey/releases"
          $binDL = (Invoke-WebRequest $releasesAHK | ConvertFrom-Json)[0].assets[0].browser_download_url
          Invoke-WebRequest "$binDL" -Out "ahk.zip"
        }else{
          $file = "AutoHotkey_$($compileTag -replace '^v', '').zip"
          Invoke-WebRequest "https://github.com/AutoHotkey/AutoHotkey/releases/download/$compileTag/$file" -Out "ahk.zip"
        }
        Expand-Archive "ahk.zip" -Force

        $inList = "${{inputs.in}}" -split "`n+" | Where-Object { $_ -ne "" }
        $outRaw = "${{inputs.out}}"

        if($outRaw -ne ""){
          $outList = $outRaw -split "`n+"
        }else{
          $outList = @()
        }

        $bits = "${{inputs.bits}}"

        for ($i = 0; $i -lt $inList.Count; $i++) {
          $compileName = $inList[$i].Trim()

          if ($i -lt $outList.Count) {
            $outName = $outList[$i].Trim()
          } else {
            $outName = ""
          }

          $argList = "/base .\ahk\AutoHotkey$bits.exe /in `"$compileName`""

          if ($outName -ne "") {
            $argList += " /out `"$outName`""
          }

          Write-Host "Compiling $compileName -> $outName ($i/$inList.Count)"

          Start-Process -FilePath $compileExe -ArgumentList $argList -Wait
        }

branding:
  color: blue
  icon: file-plus
